-- CONFIGURACIÓN GENERAL
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

-- TABLA CLIENTE
CREATE TABLE client (
                        clientrut        VARCHAR(255) NOT NULL,
                        client_birthday  VARCHAR(255),
                        client_email     VARCHAR(255),
                        client_name      VARCHAR(255),
                        visits_per_month INTEGER,
                        PRIMARY KEY (clientrut)
);

-- DATOS DE EJEMPLO PARA CLIENTES
INSERT INTO client (clientrut,
                    client_birthday,
                    client_email,
                    client_name,
                    visits_per_month
) VALUES ('11111111-1', '15-04', 'l@g.com', 'Lalo', 4),
         ('11111111-3', '24-04', 'p@g.com', 'Pedro', 4),
         ('11111111-4', '30-05', 'c@g.com', 'Cia', 3),
         ('11111111-2', '15-04', 'l@g.com', 'Lalo 2', 3),
         ('12345678-9', '1990-05-12', 'catalinaloopza@gmail.com', 'Lenovo HP', 1);


-- TABLA BOOKING
CREATE TABLE booking (
                         id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
                         iva                      VARCHAR(255),
                         base_price               VARCHAR(255),
                         booking_date             DATE,
                         booking_status           VARCHAR(255),
                         booking_time             TIME(6),
                         booking_time_end         TIME(6),
                         clients_emails           VARCHAR(255),
                         clients_names            VARCHAR(255),
                         clientsrut               VARCHAR(255),
                         discounts                VARCHAR(255),
                         laps_or_max_time_allowed INTEGER,
                         num_of_people            INTEGER,
                         total_amount             INTEGER,
                         total_price              VARCHAR(255),
                         total_with_iva           VARCHAR(255),
                         PRIMARY KEY (id)
);

-- DATOS DE EJEMPLO PARA BOOKINGS
INSERT INTO booking (
    id, iva, base_price, booking_date, booking_status, booking_time, booking_time_end,
    clients_emails, clients_names, clientsrut, discounts,
    laps_or_max_time_allowed, num_of_people, total_amount, total_price, total_with_iva
) VALUES
      (7, '19', '25000', '2025-06-15', 'pendiente', '13:00:00', '13:40:00',
       'catalinaloopza@gmail.com, b@b.x', 'Ana, Tito', '11111111-4,11111111-2', 'visitas,visitas,', 20, 2, 53550, '22500,22500,', '26775,26775'),

      (4, '19', '20000', '2025-04-15', 'pendiente', '13:00:00', '13:35:00',
       'catalinaloopza@gmail.com,a@a.x, c@c.x, a@a.x, b@b.x',
       'Lalo, Pepe, Luz, Maria, Ana', '11111111-1,11111111-3,11111111-0,11111110-0,11111100-0,11111000-0',
       'cumpleaños,cumpleaños,no,no,no,no,', 15, 6, NULL, '10000,20000,20000,20000,20000,20000,', NULL),

      (5, '19', '20000', '2025-04-15', 'confirmada', '13:00:00', '13:35:00',
       'catalinaloopza@gmail.com,lapaez@gmail.com, c@c.x, a@a.x, b@b.x',
       'Lalo, Pepe, Luz, Maria, Ana, Tito', '11111111-1,11111111-3,11111111-0,11111110-0,11111111-4,11111111-2',
       'cumpleaños,visitas,no,no,integrantes,cumpleaños,', 15, 6, NULL, '10000,18000,20000,20000,16000,10000,', NULL),

      (3, '19', '20000', '2025-04-15', 'confirmada', '12:00:00', '12:35:00',
       'catalinaloopza@gmail.com,lapaez@gmail.com, c@c.x, a@a.x, b@b.x',
       'Lalo, Pepe, Luz, Maria, Ana', '11111111-1,11111111-3,11111111-0,11111110-0,11111100-0,11111000-0',
       'cumpleaños,integrantes,no,no,no,no,', 15, 6, NULL, '50,16000,20000,20000,20000,20000,', NULL),

      (6, '19', '20000', '2025-05-15', 'confirmada', '13:00:00', '13:35:00',
       'catalinaloopza@gmail.com,lapaez@gmail.com, c@c.x, a@a.x, b@b.x',
       'Lalo, Pepe, Luz, Maria, Ana, Tito', '11111111-1,11111111-3,11111111-0,11111110-0,11111111-4,11111111-2',
       'visitas,visitas,no,no,integrantes,integrantes,', 15, 6, 128520, '18000,18000,20000,20000,16000,16000,', '21420,21420,23800,23800,19040,19040'),

      (8, '19', '25000', '2025-06-12', 'cancelada', '14:20:00', '15:00:00',
       'catalinaloopza@gmail.com', 'Lenovo HP', '12345678-9', 'no,', 20, 1, 29750, '25000,', '29750');
