apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-discounts2-deployment
  labels:
    app: ms-discounts2-deployment
spec:
  selector:
    matchLabels:
      app: ms-discounts2-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-discounts2-deployment
    spec:
      containers:
        - name: ms-discounts2
          image: calpz/ms-discounts2-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          env:
            - name: SERVER_PORT
              value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-discounts2-service
  labels:
    app: ms-discounts2-service
spec:
  selector:
    app: ms-discounts2-deployment
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP