apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-discounts1-deployment
  labels:
    app: ms-discounts1-deployment
spec:
  selector:
    matchLabels:
      app: ms-discounts1-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-discounts1-deployment
    spec:
      containers:
        - name: ms-discounts1
          image: calpz/ms-discounts1-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          env:
            - name: SERVER_PORT
              value: "0"

---
apiVersion: v1
kind: Service
metadata:
  name: ms-discounts1-service
  labels:
    app: ms-discounts1-service
spec:
  selector:
    app: ms-discounts1-deployment
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP