apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-special-rates-deployment
  labels:
    app: ms-special-rates-deployment
spec:
  selector:
    matchLabels:
      app: ms-special-rates-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-special-rates-deployment
    spec:
      containers:
        - name: ms-special-rates
          image: calpz/ms-special-rates-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8007
          env:
            - name: SERVER_PORT
              value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-special-rates-service
  labels:
    app: ms-special-rates-service
spec:
  selector:
    app: ms-special-rates-deployment
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP