apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  DB_USERNAME_BOOKING: cG9zdGdyZXM=
  DB_PASSWORD_BOOKING: MjAyMA==
  DB_USERNAME_RACK: cG9zdGdyZXM=
  DB_PASSWORD_RACK: MjAyMA==